### ISSUE TITLE
Issues with generating "reconstructed_poses.hdf5"

### ISSUE THREAD

**Issue by treesturn** [zju3dv/neuralbody#161]
I attempted to use the suggested videoavatars repo to generate the reconstructed_poses.hdf5 poses using the sample people_snapshot dataset: masks.hdf5, keypoints.hdf5 and camera.pkl, specifically the run_step1.sh file, but this is the error im getting, does anyone know how to get the 'reconstructed_poses.hdf5'

![image](https://github.com/zju3dv/neuralbody/assets/77474648/ad8a55ec-5171-4ca1-9a27-d1d2e742f253)

**Comment by kitylam9** [comment]
Need to use the SMPL v1.0.0 model file, basicmodel_f_lbs_10_207_0_v1.0.0.pkl
However, even the model is correct, the training is not correct after some point, the error I got is
Traceback (most recent call last):
  File "step1_pose.py", line 380, in <module>
    args.body_height, args.nohands, args.display)
  File "step1_pose.py", line 322, in main
    fit_pose(current_frame, last_smpl, frustum, nohands, debug_rn)
  File "step1_pose.py", line 197, in fit_pose
    bgcolor=0, num_channels=1)
  File "/home/lambeyond/.local/lib/python2.7/site-packages/chumpy/ch.py", line 129, in __new__
    result.set(**defs)
  File "/home/lambeyond/.local/lib/python2.7/site-packages/chumpy/ch.py", line 482, in set
    self.__setattr__(kwall[-1], kwargs[kwall[-1]], None)
  File "/home/lambeyond/.local/lib/python2.7/site-packages/chumpy/ch.py", line 407, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by pengsida** [comment]
Please open an issue at the repository of videoavatars.
