### ISSUE TITLE
limits of cuda hash

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/neuralbody#47]
**I try to test with CMU data, and I prepared the dataset following the zju_mocap structure.
But when I run the train_net.py code, it returns the error like this, 

I set the batch size 1 and am very confused about this issue.**

Traceback (most recent call last):
  File "train_net.py", line 108, in <module>
    main()
  File "train_net.py", line 104, in main
    train(cfg, network)
  File "train_net.py", line 44, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/data/neuralbody/lib/train/trainers/trainer.py", line 46, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/train/trainers/if_nerf_clight.py", line 19, in forward
    ret = self.renderer.render(batch)
  File "/data/neuralbody/lib/networks/renderer/if_clight_renderer.py", line 103, in render
    feature_volume = self.net.encode_sparse_voxels(sp_input)
  File "lib/networks/latent_xyzc.py", line 37, in encode_sparse_voxels
    feature_volume = self.xyzc_net(xyzc)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "lib/networks/latent_xyzc.py", line 185, in forward
    net = self.conv0(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/spconv-1.2.1-py3.8-linux-x86_64.egg/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/spconv-1.2.1-py3.8-linux-x86_64.egg/spconv/conv.py", line 169, in forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/usr/local/lib/python3.8/dist-packages/spconv-1.2.1-py3.8-linux-x86_64.egg/spconv/ops.py", line 91, in get_indice_pairs
    res = torch.ops.spconv.get_indice_pairs(indices, batch_size, out_shape,
RuntimeError: /root/spconv/src/spconv/spconv_ops.cc 39
batchSize * outputVolume < std::numeric_limits<int>::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits<int>::max() = 2e9

**Comment by pengsida** [comment]
Look very strange. I did not encounter this problem.

**Comment by pengsida** [comment]
Please check if your data format is correct.

**Comment by neilgogogo** [comment]
I got the reason that I need to increase the voxel size because the out_sh is so large when I use my own data, so it will output the error that batchsize*outputvolume is so large. Because the outputvolume=out_sh[0]*out_sh[1]*out_sh[2]

**Comment by neilgogogo** [comment]
oh, I find that resizing the voxel will lead to a GPU memory issue. I recheck my dataset and find that the extrinsic parameter is not correct. now it works;)
