### ISSUE TITLE
which platform do you visualize the mesh

### ISSUE THREAD

**Issue by zshyang** [zju3dv/neuralbody#94]
I tried to run the following code.
```
python tools/render_mesh.py --exp_name female3c --dataset people_snapshot --mesh_ind 226
```
But got the following error:
```
Traceback (most recent call last):
  File "tools/render_mesh.py", line 98, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "/home/george/george/projects/neuralbody/tools/render/color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "/home/george/george/projects/neuralbody/tools/render/cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "/home/george/george/projects/neuralbody/tools/render/render.py", line 41, in __init__
    glutInit()
  File "/home/george/.local/lib/python3.8/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/george/.local/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```
The problem seems to be that I need to reinstall OpenGL. But I could only see wheels with a windows version. So I would like to verify with the platform do you test this rendering mesh code.

**Comment by pengsida** [comment]
I run the code on a computer with Ubuntu 16.04.

**Comment by tleyden** [comment]
I hit the same error, and running `sudo apt-get install freeglut3-dev` got past that error
